# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
    - nodejs_version: 8
    - nodejs_version: 9
    - nodejs_version: 10
    - nodejs_version: 11

install:
  - npm install

build: off

test_script:
  - node --version
  - npm --version
  - set PATH=.\node_modules\.bin;%PATH%
  - npm test
